name: Telegram Gate

on:
  issue_comment:
    types: created
  issues:
    types: [opened, edited, pinned, closed, reopened, assigned, labeled]
  pull_request:
    types:
      [opened, closed, edited, ready_for_review, review_requested, reopened]
  pull_request_review_comment:
    types: created
  push:

jobs:
  build:
    name: Telegram Gate
    runs-on: ubuntu-latest
    steps:
      - name: Notifier
        uses: ethyaan/tgate-action@beta
        if: always()
        with:
         token: ${{secrets.token}}
         to: ${{secrets.to}}
         thread_id: ${{secrets.threadid}}
         disable_web_page_preview: false
         disable_notification: true
